OrgMat/OrgMat/Controllers/CriticidadeController.cs
using Microsoft.AspNetCore.Mvc;
using OrgMat.Data;
using OrgMat.Models;
using Microsoft.EntityFrameworkCore;

namespace OrgMat.Controllers
{
    public class CriticidadeController : Controller
    {
        // Construtor
        private readonly ApplicationDbContext contexto;

        public CriticidadeController(ApplicationDbContext contexto)
        {
            this.contexto = contexto;
        }
        // Fim - Construtor

        //Pagina de Lista
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var criticidades = await contexto.Criticidade.ToListAsync();
            return View(criticidades);
        }

        //Pagina de Cadastro
        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        // Criando um novo Criticidade
        [HttpPost]
        public async Task<IActionResult> Create(CriticidadeModel createCriticidadeRequest)
        {
            var criticidade = new CriticidadeModel
            {
                criticidade = createCriticidadeRequest.criticidade
            };

            contexto.Criticidade.Add(criticidade);
            try
            {
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        // Fim - Criando um novo Tipo

        //Visualização
        [HttpGet]
        public async Task<IActionResult> Visualizar(int id)
        {
            var criticidade = await contexto.Criticidade.FirstOrDefaultAsync(c => c.id_criticidade == id);
            return View(criticidade);
        }
        // Fim - Visualização

        //Atualização
        // GET - Página de edição
        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var criticidade = await contexto.Criticidade.FirstOrDefaultAsync(c => c.id_criticidade == id);
            if (criticidade == null)
            {
                return NotFound();
            }
            return View(criticidade);
        }

        //Atualização
        // POST - Atualizar
        [HttpPost]
        public async Task<IActionResult> Atualizar(CriticidadeModel updateCriticidadeRequest)
        {
            var criticidade = await contexto.Criticidade.FindAsync(updateCriticidadeRequest.id_criticidade);
            
            if (criticidade == null)
            {
                return NotFound();
            }
            criticidade.criticidade = updateCriticidadeRequest.criticidade;

            try
            {
                await contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        // Fim - Atualização

        //Deletar
        [HttpPost]
        public async Task<IActionResult> Deletar(CriticidadeModel deleteCriticidadeRequest)
        {
            var criticidade = await contexto.Criticidade.FindAsync(deleteCriticidadeRequest.id_criticidade);

            if (criticidade == null)
            {
                return NotFound();
            }
            contexto.Criticidade.Remove(criticidade);
            await contexto.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

OrgMat/OrgMat/Controllers/FornecedorController.cs
using Microsoft.AspNetCore.Mvc;
using OrgMat.Data;
using OrgMat.Models;
using Microsoft.EntityFrameworkCore;

namespace OrgMat.Controllers
{
    public class FornecedorController : Controller
    {
        // Construtor
        private readonly ApplicationDbContext contexto;

        public FornecedorController(ApplicationDbContext contexto)
        {
            this.contexto = contexto;
        }
        // Fim - Construtor

        //Pagina de Lista
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var fornecedores = await contexto.Fornecedor.ToListAsync();
            return View(fornecedores);
        }

        //Pagina de Cadastro
        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        // Criando um novo Fornecedor
        [HttpPost]
        public async Task<IActionResult> Create([Bind("fornecedor,cnpj,endereco,telefone,email,vendedor")] FornecedorModel createFornecedorRequest)
        {
            var fornecedor = new FornecedorModel
            {
                fornecedor = createFornecedorRequest.fornecedor,
                cnpj = createFornecedorRequest.cnpj,
                endereco = createFornecedorRequest.endereco,
                telefone = createFornecedorRequest.telefone,
                email = createFornecedorRequest.email,
                vendedor = createFornecedorRequest.vendedor
            };
            contexto.Fornecedor.Add(fornecedor);
            try
            {
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.InnerException.Message);
            }
        }

        // Fim - Criando um novo Fornecedor

        //Visualização
        [HttpGet]
        public async Task<IActionResult> Visualizar(int id)
        {
            var fornecedor = await contexto.Fornecedor.FirstOrDefaultAsync(f => f.id_fornecedor == id);
            return View(fornecedor);
        }
        // Fim - Visualização

        //Atualização
        // GET - Página de edição
        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var fornecedor = await contexto.Fornecedor.FirstOrDefaultAsync(f => f.id_fornecedor == id);
            if (fornecedor == null)
            {
                return NotFound();
            }
            return View(fornecedor);
        }

        //Atualização
        // POST - Atualizar
        [HttpPost]
        public async Task<IActionResult> Atualizar(FornecedorModel updateFornecedorRequest)
        {
            var fornecedor = await contexto.Fornecedor.FindAsync(updateFornecedorRequest.id_fornecedor);

            if (fornecedor == null)
            {
                return NotFound();
            }
            fornecedor.fornecedor = updateFornecedorRequest.fornecedor;
            fornecedor.cnpj = updateFornecedorRequest.cnpj;
            fornecedor.endereco = updateFornecedorRequest.endereco;
            fornecedor.telefone = updateFornecedorRequest.telefone;
            fornecedor.email = updateFornecedorRequest.email;
            fornecedor.vendedor = updateFornecedorRequest.vendedor;

            try
            {
                await contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        // Fim - Atualização

        //Deletar
        [HttpPost]
        public async Task<IActionResult> Deletar(FornecedorModel deleteFornecedorRequest)
        {
            var fornecedor = await contexto.Fornecedor.FindAsync(deleteFornecedorRequest.id_fornecedor);

            if (fornecedor == null)
            {
                return NotFound();
            }
            contexto.Fornecedor.Remove(fornecedor);
            await contexto.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

OrgMat/OrgMat/Controllers/SetorController.cs
using Microsoft.AspNetCore.Mvc;
using OrgMat.Data;
using OrgMat.Models;
using Microsoft.EntityFrameworkCore;

namespace OrgMat.Controllers
{
    public class SetorController : Controller
    {
        // Construtor
        private readonly ApplicationDbContext contexto;

        public SetorController(ApplicationDbContext contexto)
        {
            this.contexto = contexto;
        }
        // Fim - Construtor

        //Pagina de Lista
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var setores = await contexto.Setor.ToListAsync();
            return View(setores);
        }

        //Pagina de Cadastro
        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        // Criando um novo Setor
        [HttpPost]
        public async Task<IActionResult> Create(SetorModel createSetorRequest)
        {
            var setor = new SetorModel
            {
                setor = createSetorRequest.setor
            };

            contexto.Setor.Add(setor);
            try
            {
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        // Fim - Criando um novo Setor

        //Visualização
        [HttpGet]
        public async Task<IActionResult> Visualizar(int id)
        {
            var setor = await contexto.Setor.FirstOrDefaultAsync(s => s.id_setor == id);
            return View(setor);
        }
        // Fim - Visualização

        //Atualização
        // GET - Página de edição
        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var setor = await contexto.Setor.FirstOrDefaultAsync(s => s.id_setor == id);
            if (setor == null)
            {
                return NotFound();
            }
            return View(setor);
        }

        //Atualização
        // POST - Atualizar
        [HttpPost]
        public async Task<IActionResult> Atualizar(SetorModel updateSetorRequest)
        {
            var setor = await contexto.Setor.FindAsync(updateSetorRequest.id_setor);
            
            if (setor == null)
            {
                return NotFound();
            }
            setor.setor = updateSetorRequest.setor;

            try
            {
                await contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        // Fim - Atualização

        //Deletar
        [HttpPost]
        public async Task<IActionResult> Deletar(SetorModel deleteSetorRequest)
        {
            var setor = await contexto.Setor.FindAsync(deleteSetorRequest.id_setor);

            if (setor == null)
            {
                return NotFound();
            }
            contexto.Setor.Remove(setor);
            await contexto.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

OrgMat/OrgMat/Controllers/TipoController.cs
using Microsoft.AspNetCore.Mvc;
using OrgMat.Data;
using OrgMat.Models;
using Microsoft.EntityFrameworkCore;

namespace OrgMat.Controllers
{
    public class TipoController : Controller
    {
        // Construtor
        private readonly ApplicationDbContext contexto;

        public TipoController(ApplicationDbContext contexto)
        {
            this.contexto = contexto;
        }

        // Fim - Construtor

        //Pagina de Lista
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var tipos = await contexto.Tipo.ToListAsync();
            return View(tipos);
        }


        //Pagina de Cadastro
        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        // Criando um novo Tipo
        [HttpPost]
        public async Task<IActionResult> Create(TipoModel createTipoRequest)
        {
            var tipo = new TipoModel
            {
                tipo = createTipoRequest.tipo
            };

            contexto.Tipo.Add(tipo);
            try
            {
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        // Fim - Criando um novo Tipo

        // Visualização
        [HttpGet]
        public async Task<IActionResult> Visualizar(int id)
        {
            var tipo = await contexto.Tipo.FirstOrDefaultAsync(t => t.id_tipo == id);

            return View(tipo);
        }
        // Fim - Visualização

        //Atualização
        // GET: Página de edição
        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var tipo = await contexto.Tipo.FirstOrDefaultAsync(t => t.id_tipo == id);
            if (tipo == null)
            {
                return NotFound();
            }
            return View(tipo);
        }

        // POST: Atualizar registro
        [HttpPost]
        public async Task<IActionResult> Atualizar(TipoModel updateTipoRequest)
        {
            var tipo = await contexto.Tipo.FindAsync(updateTipoRequest.id_tipo);

            if (tipo == null)
            {
                return NotFound();
            }

            tipo.tipo = updateTipoRequest.tipo;

            try
            {
                await contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        // Fim - Atualização

        //Deletar
        [HttpPost]
        public async Task<IActionResult> Deletar(TipoModel deleteTipoRequest)
        {
            var tipo = await contexto.Tipo.FindAsync(deleteTipoRequest.id_tipo);

            if (tipo == null)
            {
                return NotFound();
            }
            contexto.Tipo.Remove(tipo);
            await contexto.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

OrgMat/OrgMat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OrgMat</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OrgMat.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css">


</head>
<body>

    <header id="header" class="header fixed-top d-flex align-items-center d-print-none" style="background-color:#27187e">
        <div class="d-flex align-items-center justify-content-between">
            <a class="navbar-brand" href="#"><img src="~/images/orgmat.png" alt="OrgMat Logo" width="160"></a>
        </div>
        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">
                <!--<partial name="_LoginPartial" /> -->
            </ul>
        </nav>
    </header>

    <aside id="sidebar" class="sidebar">
        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-speedometer2"></i>Dashboard</a>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#listas_nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-card-checklist"></i><span>Listas</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="listas_nav" class="nav-content collapse" data-bs-parent="#sidebar-nav">
                    <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Material" asp-action="Index">Materiais</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Criticidade" asp-action="Index">Criticidade</a></li>
                    <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Tipo" asp-action="Index">Tipos</a></li>
                    <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Fornecedor" asp-action="Index">Fornecedor</a></li>

                </ul>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#cadastros_nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-file-earmark-plus"></i><span>Cadastros</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="cadastros_nav" class="nav-content collapse" data-bs-parent="#sidebar-nav">
                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Material" asp-action="Cadastrar">Material</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Criticidade" asp-action="Cadastrar">Criticidade</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Tipo" asp-action="Cadastrar">Tipo</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Setor" asp-action="Cadastrar">Setor</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Cliente" asp-action="Cadastrar">Cliente</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Local" asp-action="Cadastrar">Local</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Fornecedor" asp-action="Cadastrar">Fornecedor</a></li>
                </ul>
            </li>

            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Manutencao" asp-action="Index"><i class="bi bi-hammer"></i>Manutenção</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="OC" asp-action="Index"><i class="bi bi-cart2"></i>Ordem de Compra</a>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#config_nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-gear"></i><span>Configuração</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="config_nav" class="nav-content collapse" data-bs-parent="#sidebar-nav">
                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Movimentacao" asp-action="Cadastrar">Cadastrar Usuário</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Movimentacao" asp-action="Index">Usuários</a></li>
                </ul>
            </li>

           
        </ul>
    </aside>

    <main id="main" class="main">
        <div class="container-fluid px-4">
            @RenderBody()
        </div>
    </main>
    

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OrgMat - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery.inputmask/dist/jquery.inputmask.bundle.min.js"></script>
    <script src="~/lib/jquery.inputmask/dist/jquery.mask.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>